# sourceclear and docker store secrets
secrets:
- kmsKeyName: projects/<project-id>/locations/global/keyRings/<secret_keyring>/cryptoKeys/<secret_key>
  secretEnv:
    SRCCLR_API_TOKEN: <paste here>
    DOCKER_LOGIN: <paste here>

# Build Steps:
# 1. Copying the ojdbc7.jar from google cloud storage bucket to workspace
# 2. Using GCB docker-compose container with "gcr.io/cloud-builders/mvn" as base image
# 2.1 Running a bash script "docker-compose.sh" inside above GCB docker-compose container
# 3. Building GCR image with application
# Note: Edited sample.properties and enabled ojdbc7 dependency in pom.xml
# Note: docker-compose.yml is used by docker-compose in script "docker-compose.sh"
# Note: Bash script "check_oracle_table.sh" is used in "docker-compose.sh"
# Note: Dockerfile is used in step 3

steps:
- name: gcr.io/cloud-builders/gsutil
  args: ['cp', 'gs://<jdbc-bucket>/ojdbc7.jar', 'ojdbc7.jar']
- name: 'gcr.io/<project-id>/docker-compose:latest'
  entrypoint: 'bash'
  args: ['-c', 'chmod 755 ./docker-compose.sh; ./docker-compose.sh']
  secretEnv: ['SRCCLR_API_TOKEN', 'DOCKER_LOGIN']
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "gcr.io/$PROJECT_ID/vertx-template-gcb:latest", "."]

images:
  - 'gcr.io/$PROJECT_ID/vertx-template-gcb:latest'
